apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  labels:
    app: mysql-config-map
data:
  MYSQL_DB_HOST: mysql
  #base de dato Cuotas
  MYSQL_DB_CUOTAS: topeducationcuotas
  #base de dato Estudiantes
  MYSQL_DB_ESTUDIANTES: topeducationestudiantes
   #base de dato Examenes
  MYSQL_DB_EXAMENES: topeducationexamenes