server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/arge16/microservices-data-project
          search-paths: config-data